source "https://rubygems.org"

ruby "~> 3.3"

gem "sinatra", "~> 4.0"
gem "rackup"
gem "puma", "~> 6.0"

gem "nokogiri"
gem "aws-sdk-s3", "~> 1.0"
gem "aws-sdk-sqs", "~> 1.0"
gem "aws-sdk-sns", "~> 1.0"
gem "aws-sdk-secretsmanager", "~> 1.0"
gem "aws-sdk-ssm", "~> 1.0"
gem "aws-sdk-rds", "~> 1.0"
gem "aws-sdk-lambda", "~> 1.0"
gem "aws-sdk-ec2", "~> 1.0"
gem "aws-sdk-ecs", "~> 1.0"
gem "aws-sdk-dynamodb", "~> 1.0"
gem "aws-sdk-elasticache", "~> 1.0"
gem "aws-sdk-athena", "~> 1.0"

gem "rubyzip", "~> 2.3"
gem "redis", "~> 5.0"

gem "pg", "~> 1.5"
